const fs = require('fs');
const path = require('path');

const RAW_MENU_DATA = [
  // 1. HOT & COLD BEVERAGES
  { name: 'PACKAGE DRINKS', price: 20, cat: 'Beverages', veg: true, jain: true, desc: 'Packaged drinking water bottle.' },
  { name: 'CHOICE OF COLD DRINKS (500 ML)', price: 50, cat: 'Beverages', veg: true, jain: true, desc: 'Chilled 500ml cold drink bottle.' },
  { name: 'CHOICE OF COLD DRINKS (200 ML)', price: 25, cat: 'Beverages', veg: true, jain: true, desc: 'Chilled 200ml cold drink glass/bottle.' },
  { name: 'CHOICE OF M/S COLD DRINK (200ML)', price: 40, cat: 'Beverages', veg: true, jain: true, desc: 'Special 200ml beverage choice.' },
  { name: 'FRESH LIME WATER / SODA', price: 40, cat: 'Beverages', veg: true, jain: true, desc: 'Fresh squeezed lime juice served with water or sparkling soda (sweet/salt).' },
  { name: 'TEA', price: 25, cat: 'Beverages', veg: true, jain: true, desc: 'Freshly brewed aromatic Indian milk tea with cardamom.' },
  { name: 'BLACK TEA', price: 25, cat: 'Beverages', veg: true, jain: true, desc: 'Strong brewed hot black tea.' },
  { name: 'LEMON TEA', price: 30, cat: 'Beverages', veg: true, jain: true, desc: 'Refreshing hot black tea infused with fresh lemon.' },
  { name: 'GREEN TEA', price: 50, cat: 'Beverages', veg: true, jain: true, desc: 'Healthy antioxidant-rich whole leaf green tea.' },
  { name: 'COFFEE', price: 35, cat: 'Beverages', veg: true, jain: true, desc: 'Steaming rich frothy milk coffee.' },
  { name: 'BLACK COFFEE', price: 30, cat: 'Beverages', veg: true, jain: true, desc: 'Freshly brewed aromatic black coffee.' },
  { name: 'HOT & COLD MILK', price: 40, cat: 'Beverages', veg: true, jain: true, desc: 'Fresh dairy milk served piping hot or chilled.' },
  { name: 'CHOICE OF LASSI', price: 60, cat: 'Beverages', veg: true, jain: true, desc: 'Thick creamy Punjabi yogurt lassi (sweet/salted).' },
  { name: 'JAL JEERA', price: 40, cat: 'Beverages', veg: true, jain: true, desc: 'Spiced digestive cumin and mint cooler.' },
  { name: 'COLD COFFEE', price: 60, cat: 'Beverages', veg: true, jain: true, desc: 'Rich blended iced coffee with milk and cocoa dusting.' },
  { name: 'COLD COFFEE WITH ICE CREAM', price: 90, cat: 'Beverages', veg: true, jain: true, desc: 'Thick blended iced coffee topped with a scoop of vanilla ice cream.' },
  { name: 'BUTTER MILK', price: 50, cat: 'Beverages', veg: true, jain: true, desc: 'Chilled spiced chaas churned with roasted cumin and coriander.' },

  // 2. MOCKTAIL COUNTER
  { name: 'PINA COLADA', price: 80, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Tropical pineapple juice blended with coconut cream and crushed ice.' },
  { name: 'VIRGIN MOJITO', price: 100, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Muddled fresh mint leaves, lime chunks, cane syrup, and sparkling soda.' },
  { name: 'VIRGIN COLADA', price: 110, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Creamy coconut cream cooler with fresh pineapple.' },
  { name: 'SUPPER COOLER', price: 110, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Signature refreshing fruit spritzer with citrus herbs.' },
  { name: 'GREEN RIVER', price: 120, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Kiwi and green apple cooler with fizz.' },
  { name: 'BLUE LAGOON', price: 120, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Curacao citrus cordial layered with sprite and lime.' },
  { name: 'MANGO DELIGHT', price: 120, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Luscious Alphonso mango nectar refresher.' },
  { name: 'ORANGE DELIGHT', price: 120, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Sun-ripened orange citrus cooler.' },
  { name: 'FRUITE PUNCH', price: 130, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Exotic blend of tropical fruit juices topped with cream.' },
  { name: 'CHOICE OF SHAKE (VANILLA)', price: 130, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Thick creamy vanilla milkshake.' },
  { name: 'CHOICE OF SHAKE (STRAWBERRY)', price: 130, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Sweet strawberry thick milkshake.' },
  { name: 'CHOICE OF SHAKE (BANANA)', price: 130, cat: 'Mocktails & Shakes', veg: true, jain: true, desc: 'Wholesome fresh banana milkshake.' },

  // 3. BREAKFAST
  { name: 'SPECIAL MAGGI', price: 100, cat: 'Breakfast', veg: true, jain: false, desc: 'Hot wok-tossed Maggi noodles with butter, peas, and mild spices.' },
  { name: 'IDLY WITH SAMBHAR CHUTNEY', price: 50, cat: 'Breakfast', veg: true, jain: true, desc: 'Steamed fluffy rice-lentil cakes served with hot sambhar and coconut chutney.' },
  { name: 'SAMBHAR VADA', price: 80, cat: 'Breakfast', veg: true, jain: true, desc: 'Crispy fried medu vadas dipped in aromatic piping hot sambhar.' },
  { name: 'PLAIN DOSA', price: 80, cat: 'Breakfast', veg: true, jain: true, desc: 'Crispy golden fermented crepe served with sambhar and chutney.' },
  { name: 'MASALA DOSA', price: 100, cat: 'Breakfast', veg: true, jain: false, desc: 'Crispy dosa wrapped around seasoned spiced potato masala.' },
  { name: 'CUTTING MASALA DOSA', price: 120, cat: 'Breakfast', veg: true, jain: false, desc: 'Sliced crispy dosa stuffed with signature potato bhaji and ghee.' },
  { name: 'GINI DOSA', price: 150, cat: 'Breakfast', veg: true, jain: false, desc: 'Mumbai-style rolled street dosa with spicy schezwan vegetables and melted cheese.' },
  { name: 'SCHEZWAN MASALA DOSA', price: 150, cat: 'Breakfast', veg: true, jain: false, desc: 'Fiery wok-tossed Schezwan sauce spread over golden dosa with potato filling.' },
  { name: 'CHEESE MUSHROOM DOSA', price: 150, cat: 'Breakfast', veg: true, jain: false, desc: 'Sauteed mushrooms and molten cheese encased in a crisp crepe.' },
  { name: 'MYSORE MASALA DOSA', price: 150, cat: 'Breakfast', veg: true, jain: false, desc: 'Classic Mysore red chutney smeared inside crisp dosa with spicy potato mash.' },
  { name: 'GHEE PODI MASALA DOSA', price: 150, cat: 'Breakfast', veg: true, jain: false, desc: 'Roasted gunpowder spice podi and desi ghee sprinkled over masala dosa.' },
  { name: 'UPMA', price: 60, cat: 'Breakfast', veg: true, jain: true, desc: 'Semolina roasted with mustard seeds, curry leaves, and green chillies.' },
  { name: 'UTTAPAM', price: 60, cat: 'Breakfast', veg: true, jain: true, desc: 'Soft thick savory South Indian pancake.' },
  { name: 'RAWA DOSA', price: 80, cat: 'Breakfast', veg: true, jain: true, desc: 'Lacy, crispy semolina crepe spiced with black pepper and cumin.' },
  { name: 'RAWA MASALA DOSA', price: 110, cat: 'Breakfast', veg: true, jain: false, desc: 'Crispy semolina dosa folded over savory spiced potato masala.' },
  { name: 'CORN FLAKE WITH MILK', price: 100, cat: 'Breakfast', veg: true, jain: true, desc: 'Crunchy golden corn flakes served with a bowl of hot sweetened milk.' },
  { name: 'BREAD TOAST (WITH BUTTER & JAM)', price: 50, cat: 'Breakfast', veg: true, jain: true, desc: 'Four slices of golden toasted bread served with butter and fruit jam.' },
  { name: 'SPECIAL POHA', price: 90, cat: 'Breakfast', veg: true, jain: false, desc: 'Flattened rice tempered with mustard, roasted peanuts, onions, and turmeric.' },
  { name: 'POORI BHAJI', price: 120, cat: 'Breakfast', veg: true, jain: false, desc: 'Puffed golden whole wheat pooris served with spiced aloo bhaji.' },
  { name: 'CHHOLEY BHATURE', price: 140, cat: 'Breakfast', veg: true, jain: false, desc: 'Fluffy golden bhaturas paired with authentic Punjabi spiced chickpea curry.' },
  { name: 'ALOO PARATHA WITH CURD', price: 100, cat: 'Breakfast', veg: true, jain: false, desc: 'Tawa griddled flatbread stuffed with spiced potato mash, served with curd.' },
  { name: 'GOBHI PARATHA WITH CURD', price: 110, cat: 'Breakfast', veg: true, jain: false, desc: 'Flaky paratha packed with grated cauliflower and spices, served with curd.' },
  { name: 'PANEER PARATHA WITH CURD', price: 150, cat: 'Breakfast', veg: true, jain: true, desc: 'Rich flatbread stuffed with seasoned cottage cheese, served with curd.' },
  { name: 'VEG SANDWICH', price: 80, cat: 'Breakfast', veg: true, jain: false, desc: 'Fresh bread sandwich with sliced cucumbers, tomatoes, and mint chutney.' },
  { name: 'VEG GRILLED SANDWICH', price: 100, cat: 'Breakfast', veg: true, jain: false, desc: 'Toasted panini grilled vegetable sandwich with herbs and butter.' },
  { name: 'OMELETTE (P/M)', price: 100, cat: 'Breakfast', veg: false, jain: false, desc: 'Farm-fresh two-egg omelette (Plain or Masala with onions and chillies).' },
  { name: 'BREAD OMELETTE', price: 110, cat: 'Breakfast', veg: false, jain: false, desc: 'Classic railway junction style double egg omelette wrapped around toasted bread.' },
  { name: 'BOILED EGG', price: 80, cat: 'Breakfast', veg: false, jain: false, desc: 'Two farm eggs hard-boiled and sprinkled with rock salt and pepper.' },
  { name: 'FRENCH TOAST', price: 110, cat: 'Breakfast', veg: false, jain: false, desc: 'Golden egg-battered bread pan-seared with butter.' },
  { name: 'CHICKEN SANDWICH', price: 200, cat: 'Breakfast', veg: false, jain: false, desc: 'Shredded chicken tossed with creamy mayo and pepper in grilled bread.' },

  // 4. FRESH GREEN SALAD'S & CURD
  { name: 'GREEN SALAD', price: 90, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Fresh garden slices of cucumber, carrot, tomato, and lemon wedges.' },
  { name: 'ONION SALAD', price: 60, cat: 'Salads & Raita', veg: true, jain: false, desc: 'Thinly sliced crunchy red onion rings sprinkled with chaat masala.' },
  { name: 'KACHUMBAR SALAD', price: 90, cat: 'Salads & Raita', veg: true, jain: false, desc: 'Diced cucumbers, tomatoes, and onions tossed with lime and coriander.' },
  { name: 'SPROUTED SALAD', price: 110, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Nutritious sprouted moong and gram tossed with lemon and mild spices.' },
  { name: 'ALOO CHANA CHAT', price: 100, cat: 'Salads & Raita', veg: true, jain: false, desc: 'Tangy street-style boiled potato and kabuli chana chaat.' },
  { name: 'GREEN PEAS CHAT', price: 90, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Tender steamed green peas sauteed with tangy chaat seasonings.' },
  { name: 'PAPAD (DRY/FRY)', price: 25, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Crispy roasted or deep-fried urad dal papad.' },
  { name: 'MASALA PAPAD', price: 40, cat: 'Salads & Raita', veg: true, jain: false, desc: 'Crisp roasted papad topped with spicy onion-tomato kachumber.' },
  { name: 'PLAIN CURD', price: 40, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Fresh creamy set dairy curd.' },
  { name: 'VEG RAITA', price: 70, cat: 'Salads & Raita', veg: true, jain: false, desc: 'Chilled whisked yogurt with finely diced cucumber and roasted cumin.' },
  { name: 'BOONDI RAITA', price: 70, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Crisp gram flour boondi soaked in seasoned chilled yogurt.' },
  { name: 'PINEAPPLE RAITA', price: 110, cat: 'Salads & Raita', veg: true, jain: true, desc: 'Sweet and tangy chilled yogurt infused with juicy pineapple chunks.' },

  // 5. FROM THE SOUP KETTLE
  { name: 'VEG HOT & SOUR SOUP', price: 100, cat: 'Soups & Shorba', veg: true, jain: false, desc: 'Fiery and tangy Indo-Chinese vegetable broth.' },
  { name: 'VEG MANCHOW SOUP', price: 110, cat: 'Soups & Shorba', veg: true, jain: false, desc: 'Thick dark soy garlic soup loaded with vegetables and fried crispy noodles.' },
  { name: 'VEG SWEET CORN SOUP', price: 110, cat: 'Soups & Shorba', veg: true, jain: true, desc: 'Silky mild sweet corn broth with tender kernels.' },
  { name: 'VEG LEMON CORIENDER SOUP', price: 110, cat: 'Soups & Shorba', veg: true, jain: false, desc: 'Clear refreshing vegetable soup accented with fresh lemon and coriander.' },
  { name: 'TOMATO SOUP', price: 120, cat: 'Soups & Shorba', veg: true, jain: true, desc: 'Velvety ripe tomato soup served with crispy golden croutons.' },
  { name: 'TOMATO DHANIYA KA SHORBA', price: 150, cat: 'Soups & Shorba', veg: true, jain: true, desc: 'Traditional slow-simmered Indian spiced tomato and fresh coriander broth.' },
  { name: 'CHICKEN HOT & SOUR SOUP', price: 130, cat: 'Soups & Shorba', veg: false, jain: false, desc: 'Spicy pepper and vinegar chicken soup with egg ribbons.' },
  { name: 'CHICKEN MANCHOW SOUP', price: 130, cat: 'Soups & Shorba', veg: false, jain: false, desc: 'Hearty chicken garlic soup topped with crunchy fried noodles.' },
  { name: 'CHICKEN SWEET CORN SOUP', price: 130, cat: 'Soups & Shorba', veg: false, jain: false, desc: 'Gentle creamy broth with shredded chicken and sweet corn.' },
  { name: 'CHICKEN LEMON CORIENDER SOUP', price: 130, cat: 'Soups & Shorba', veg: false, jain: false, desc: 'Zesty chicken broth flavored with fresh lemon juice and green coriander.' },
  { name: 'CHICKEN SHORBA', price: 180, cat: 'Soups & Shorba', veg: false, jain: false, desc: 'Rich royal Awadhi chicken extract simmered with whole spices.' },

  // 6. FROM THE VEG STARTER
  { name: 'HARA BHARA KEBAB', price: 200, cat: 'Veg Starters', veg: true, jain: false, desc: 'Pan-seared spinach, green pea and potato patties spiced with garam masala.' },
  { name: 'ADRAKI TIKKI', price: 200, cat: 'Veg Starters', veg: true, jain: false, desc: 'Ginger-infused crisp vegetable tikkis served with mint dip.' },
  { name: 'VEG CORN KEBAB', price: 200, cat: 'Veg Starters', veg: true, jain: false, desc: 'Golden sweet corn and vegetable mince skewers.' },
  { name: 'VEG SEEKH KEBAB', price: 250, cat: 'Veg Starters', veg: true, jain: false, desc: 'Minced mixed vegetables seasoned with herbs and roasted on tandoor skewers.' },
  { name: 'VEG CUTLET', price: 150, cat: 'Veg Starters', veg: true, jain: false, desc: 'Crumb-fried crispy vegetable cutlets with tomato dip.' },
  { name: 'VEG PAKODA', price: 150, cat: 'Veg Starters', veg: true, jain: false, desc: 'Assorted seasonal vegetables dipped in spiced gram flour batter and fried.' },
  { name: 'VEG KULHAD KEBAB', price: 220, cat: 'Veg Starters', veg: true, jain: false, desc: 'Smoky clay-pot roasted vegetable kebabs served with chutney.' },
  { name: 'DAHI KEBAB', price: 250, cat: 'Veg Starters', veg: true, jain: true, desc: 'Melt-in-mouth hung curd patties with a golden crispy crust.' },
  { name: 'PANEER PAKODA', price: 200, cat: 'Veg Starters', veg: true, jain: true, desc: 'Batter-fried succulent cottage cheese slices with chaat masala.' },
  { name: 'PANEER KURKURE ROLL', price: 220, cat: 'Veg Starters', veg: true, jain: true, desc: 'Crispy coated paneer fingers rolled in crushed spiced flakes.' },
  { name: 'CHANA ROAST', price: 150, cat: 'Veg Starters', veg: true, jain: false, desc: 'Pan-roasted spicy kabuli chana tossed with curry leaves and onions.' },
  { name: 'MUSHROOM PAKODA', price: 180, cat: 'Veg Starters', veg: true, jain: false, desc: 'Whole fresh mushrooms batter-fried to golden crispness.' },
  { name: 'FINGER CHIPS', price: 120, cat: 'Veg Starters', veg: true, jain: true, desc: 'Crispy salted potato French fries.' },
  { name: 'PANEER TIKKA', price: 250, cat: 'Veg Starters', veg: true, jain: true, desc: 'Charcoal-grilled cottage cheese cubes marinated in yogurt and tandoori spices.' },
  { name: 'PANEER PUDINA TIKKA', price: 250, cat: 'Veg Starters', veg: true, jain: true, desc: 'Tandoor-roasted paneer cubes infused with fresh mint and coriander.' },
  { name: 'PANEER LEHSUNI TIKKA', price: 250, cat: 'Veg Starters', veg: true, jain: false, desc: 'Creamy paneer cubes marinated in robust roasted garlic marinade.' },
  { name: 'PANEER HARIYALI TIKKA', price: 250, cat: 'Veg Starters', veg: true, jain: true, desc: 'Vibrant green herb marinade coated paneer grilled in clay oven.' },
  { name: 'PANEER METHI SEEKH KEBAB', price: 310, cat: 'Veg Starters', veg: true, jain: true, desc: 'Grated paneer and fresh fenugreek leaves molded onto skewers and char-grilled.' },
  { name: 'PANEER SOTI BOTI', price: 220, cat: 'Veg Starters', veg: true, jain: true, desc: 'Tender bite-sized spiced paneer morsels tossed on a hot griddle.' },
  { name: 'CHEESE CORN BOWL', price: 250, cat: 'Veg Starters', veg: true, jain: true, desc: 'Baked sweet corn kernels enveloped in melted golden cheese.' },
  { name: 'SAAHI PEDRO', price: 220, cat: 'Veg Starters', veg: true, jain: true, desc: 'Chef specialty paneer and potato delicacy.' },
  { name: 'AMRITSARI SOYA TIKKA', price: 220, cat: 'Veg Starters', veg: true, jain: false, desc: 'Protein-rich soya chaap marinated in authentic Amritsari spices and grilled.' },
  { name: 'TANDOORI PLATTER(VEG)', price: 650, cat: 'Veg Starters', veg: true, jain: false, desc: 'Grand platter with Paneer Tikka, Veg Seekh, Hara Bhara Kebab, and Mushroom.' },

  // 7. FROM THE NONVEG STARTERS
  { name: 'EGG POUCH', price: 90, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Delicately poached farm eggs with black pepper.' },
  { name: 'EGG PAKODA', price: 110, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Boiled egg halves dipped in spiced batter and deep-fried.' },
  { name: 'CHICKEN PAKODA', price: 220, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Crispy fried boneless chicken fritters with mint chutney.' },
  { name: 'CHICKEN AMRITSARI(FRY)', price: 250, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Ajwain and gram flour batter-fried Punjabi style chicken.' },
  { name: 'CHICKEN TIKKA', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Boneless chicken chunks marinated in mustard oil and red spices, char-grilled.' },
  { name: 'CHICKEN BANJARA TIKKA', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Rustic nomad-style chicken tikka with pounded coriander and chillies.' },
  { name: 'CHICKEN MALAI TIKKA', price: 350, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Velvety chicken chunks coated in cashew cream, cheese, and cardamom.' },
  { name: 'CHICKEN AFGHANI TIKKA', price: 350, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Mildly spiced, creamy roasted chicken morsels.' },
  { name: 'CHICKEN HARIYALI TIKKA', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Clay oven cooked chicken in a fresh coriander, mint, and spinach marinade.' },
  { name: 'CHICKEN GARLIC TIKKA', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Tender chicken marinated in roasted garlic paste and grilled.' },
  { name: 'CHICKEN DOUBLE TADKA TIKKA', price: 350, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Smoky chicken tikka finished with a sizzling double ghee-garlic tempering.' },
  { name: 'CHEF SPECIAL CHICKEN TIKKA', price: 350, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Hotel Elite Inn secret recipe char-grilled tender chicken.' },
  { name: 'CHICKEN RESHMI KEBAB', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Silky chicken mince kebabs seasoned with roasted herbs.' },
  { name: 'CHICKEN TANGDI KEBAB', price: 300, cat: 'Non-Veg Starters', veg: false, jain: false, desc: 'Spiced chicken drumsticks grilled to smoky perfection in tandoor.' },

  // 8. CHICKEN CURRIES & MAIN COURSE
  { name: 'CHICKEN MASALA', price: 280, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Traditional homestyle chicken cooked in rich onion-tomato gravy.' },
  { name: 'CHICKEN KADAI', price: 280, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Chicken tossed with bell peppers and crushed coriander seeds in a wok.' },
  { name: 'CHICKEN HYDERABADI', price: 290, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Aromatic chicken curry enriched with fresh mint and coriander paste.' },
  { name: 'CHICKEN RARA', price: 320, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Chicken pieces simmered together with rich spiced chicken mince keema gravy.' },
  { name: 'CHICKEN BHUNA', price: 290, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Dry-roasted chicken simmered slowly until thick caramelized gravy coats each piece.' },
  { name: 'CHICKEN MAHARAJA', price: 350, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Royal Mughlai chicken preparation with cashew nut paste and saffron.' },
  { name: 'CHICKEN ASIYANA', price: 290, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'House specialty mildly spiced chicken curry.' },
  { name: 'CHICKEN ROGAN JOSH', price: 290, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Kashmiri style slow-cooked aromatic chicken in rich red gravy.' },
  { name: 'CHICKEN BHARTA', price: 320, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Finely shredded boneless chicken in a creamy, egg-enriched sauce.' },
  { name: 'CHICKEN BUTTER MASALA', price: 320, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Classic chicken in a velvety butter-tomato makhani gravy.' },
  { name: 'CHICKEN TIKKA MASALA', price: 350, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Tandoor-charred chicken tikka cubes simmered in spiced tomato gravy.' },
  { name: 'BUTTER CHICKEN BONELESS', price: 350, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Tender boneless chicken in luscious sweet-tangy makhani butter cream.' },
  { name: 'MURG MUSSALLAM (HALF)', price: 350, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Slow-cooked spiced half chicken in a royal egg-garnished Mughlai gravy.' },
  { name: 'MURG MUSSALLAM (FULL)', price: 650, cat: 'Chicken Specialities', veg: false, jain: false, desc: 'Magnificent whole chicken simmered in rich saffron-cashew Mughlai gravy.' },

  // 9. SEAFOOD & MUTTON DELICACIES
  { name: 'FISH CURRY (B/L)', price: 270, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Boneless fish fillets cooked in homestyle mustard and tomato curry.' },
  { name: 'FISH MASALA (B/L)', price: 270, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Pan-seared boneless fish in thick onion-tomato gravy.' },
  { name: 'FISH AMRITSARI CURRY', price: 270, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Crisp battered fish simmered in tangy Punjabi style gravy.' },
  { name: 'FISH CURRY BENGALI STYLE', price: 270, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Authentic Macher Jhol cooked with panch phoron and mustard oil.' },
  { name: 'FISH TIKKA MASALA', price: 300, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Charcoal-grilled fish tikka tossed in spicy masala gravy.' },
  { name: 'PRAWNS CURRY', price: 350, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Fresh prawns simmered in coastal coconut and spice gravy.' },
  { name: 'PRAWNS MASALA', price: 350, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Juicy prawns sauteed with onions, capsicum, and garam masala.' },
  { name: 'PRAWNS CURRY IN BENGALI STYLE', price: 370, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Traditional Bengali Chingri Malai Curry preparation.' },
  { name: 'TANDOORI PRAWNS MASALA', price: 370, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Clay oven charred prawns finished in a smoky masala sauce.' },
  { name: 'MUTTON CURRY', price: 380, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Tender baby goat meat slow-cooked in traditional Odisha homestyle gravy.' },
  { name: 'MUTTON MASALA', price: 380, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Mutton pieces braised in a robust, aromatic onion-tomato reduction.' },
  { name: 'BHUNA MUTTON', price: 380, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Slow pan-roasted mutton until dark, caramelized, and intensely flavorful.' },
  { name: 'MUTTON ROGAN JOSH', price: 380, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Classic Kashmiri goat curry cooked with ratan jot and Kashmiri chillies.' },
  { name: 'MUTTON RARA', price: 450, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Mutton bone-in chunks cooked along with rich spiced mutton keema.' },
  { name: 'CHAMPARAN MEAT', price: 500, cat: 'Seafood & Mutton', veg: false, jain: false, desc: 'Celebrated Ahuna earthen handi slow-cooked mutton with whole garlic pods.' },

  // 10. FROM THE INDIAN BREADS
  { name: 'RUMALI ROTI', price: 40, cat: 'Indian Breads', veg: true, jain: true, desc: 'Handkerchief-thin soft unleavened bread tossed over an inverted wok.' },
  { name: 'TAWA ROTI', price: 25, cat: 'Indian Breads', veg: true, jain: true, desc: 'Fresh whole wheat flatbread made on tawa.' },
  { name: 'BUTTER TAWA ROTI', price: 25, cat: 'Indian Breads', veg: true, jain: true, desc: 'Tawa roti basted with pure dairy butter.' },
  { name: 'TANDOORI ROTI', price: 30, cat: 'Indian Breads', veg: true, jain: true, desc: 'Whole wheat bread baked in clay tandoor.' },
  { name: 'BUTTER TANDOORI ROTI', price: 35, cat: 'Indian Breads', veg: true, jain: true, desc: 'Clay oven roti brushed with golden melted butter.' },
  { name: 'MISSI ROTI', price: 40, cat: 'Indian Breads', veg: true, jain: true, desc: 'Nutritious gram flour and wheat flatbread spiced with ajwain and kasuri methi.' },
  { name: 'PLAIN PARATHA TAWA', price: 40, cat: 'Indian Breads', veg: true, jain: true, desc: 'Layered whole wheat paratha roasted crisp on tawa.' },
  { name: 'LACHHA PARATHA', price: 40, cat: 'Indian Breads', veg: true, jain: true, desc: 'Multi-layered flaky tandoor paratha brushed with butter.' },
  { name: 'PLAIN NAAN', price: 40, cat: 'Indian Breads', veg: true, jain: true, desc: 'Traditional tear-drop shaped leavened white flour bread from clay oven.' },
  { name: 'BUTTER NAAN', price: 45, cat: 'Indian Breads', veg: true, jain: true, desc: 'Soft tandoori naan lavishly brushed with melted butter.' },
  { name: 'GARLIC NAAN', price: 55, cat: 'Indian Breads', veg: true, jain: false, desc: 'Tandoor naan topped with minced roasted garlic, coriander, and butter.' },
  { name: 'MASALA KULCHA', price: 55, cat: 'Indian Breads', veg: true, jain: false, desc: 'Leavened bread stuffed with spiced potato and onion mash.' },
  { name: 'PANEER KULCHA', price: 70, cat: 'Indian Breads', veg: true, jain: true, desc: 'Stuffed kulcha filled with seasoned grated cottage cheese.' },
  { name: 'ROTI BASKET', price: 350, cat: 'Indian Breads', veg: true, jain: true, desc: 'Assorted basket with Butter Naan, Garlic Naan, Lachha Paratha, Tandoori Roti & Missi Roti.' },

  // 11. BASMATI KE JADOO (Rice & Biryani)
  { name: 'PLAIN RICE (BASMATI)', price: 100, cat: 'Rice & Biryani', veg: true, jain: true, desc: 'Steamed long-grain aromatic Royal Basmati rice.' },
  { name: 'JEERA RICE', price: 120, cat: 'Rice & Biryani', veg: true, jain: true, desc: 'Basmati rice tempered with roasted cumin seeds and desi ghee.' },
  { name: 'VEG BIRYANI', price: 210, cat: 'Rice & Biryani', veg: true, jain: false, desc: 'Layered basmati rice with seasonal vegetables, mint, and saffron.' },
  { name: 'VEG PULAO', price: 210, cat: 'Rice & Biryani', veg: true, jain: true, desc: 'Fragrant basmati rice gently cooked with green peas, carrots, and whole spices.' },
  { name: 'CURD RICE', price: 150, cat: 'Rice & Biryani', veg: true, jain: true, desc: 'Comforting tempered curd rice with mustard seeds, curry leaves, and ginger.' },
  { name: 'LEMON RICE', price: 150, cat: 'Rice & Biryani', veg: true, jain: true, desc: 'Tangy South Indian rice tempered with turmeric, peanuts, and fresh lemon juice.' },
  { name: 'PANEER BIRYANI', price: 250, cat: 'Rice & Biryani', veg: true, jain: false, desc: 'Layered dum biryani with marinated paneer cubes and caramelized onions.' },
  { name: 'PANEER TIKKA BIRYANI', price: 280, cat: 'Rice & Biryani', veg: true, jain: false, desc: 'Smoky tandoori paneer tikka layered in aromatic spiced saffron rice.' },
  { name: 'EGG BIRYANI', price: 180, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Fragrant basmati rice layered with spiced boiled eggs and biryani masala.' },
  { name: 'CHICKEN DUM BIRYANI', price: 250, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Authentic slow-dum cooked basmati rice with tender marinated chicken pieces.' },
  { name: 'CHICKEN HYDERABADI BIRYANI', price: 270, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Spicy Hyderabadi kacchi style chicken biryani with mint and saffron.' },
  { name: 'CHICKEN ROAST BIRYANI', price: 290, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Basmati biryani topped with crispy pan-roasted spicy chicken.' },
  { name: 'CHICKEN TIKKA BIRYANI', price: 300, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Charcoal grilled chicken tikka cubes layered with fragrant biryani rice.' },
  { name: 'CHICKEN HANDI BIRYANI', price: 350, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Sealed clay handi dum biryani with rich chicken masala.' },
  { name: 'PRAWNS BIRYANI', price: 280, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Coastal spiced succulent prawns layered with long-grain basmati.' },
  { name: 'MUTTON BIRYANI', price: 350, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Royal mutton biryani with succulent baby goat meat and saffron essence.' },
  { name: 'MUTTON HANDI BIRYANI', price: 400, cat: 'Rice & Biryani', veg: false, jain: false, desc: 'Clay handi slow-cooked tender mutton biryani served with raita.' },

  // 12. CONTINENTAL & SIZZLERS
  { name: 'WHITE SAUCE PASTA VEG', price: 200, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Penne pasta tossed in rich creamy Bechamel cheese sauce with bell peppers.' },
  { name: 'RED SAUCE PASTA VEG', price: 200, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Penne pasta simmered in tangy herb tomato Arrabiata sauce.' },
  { name: 'FUSELI PASTA', price: 210, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Spiral fusilli pasta tossed with garlic, olive oil, and herbs.' },
  { name: 'MIX SAUCE PASTA', price: 220, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Pink sauce pasta combining rich cream and tangy tomato herbs.' },
  { name: 'WHITE SAUCE CHICKEN PASTA', price: 280, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Creamy white sauce pasta with tender chicken breast strips.' },
  { name: 'RED SAUCE CHICKEN PASTA', price: 280, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Spicy chicken penne tossed in robust tomato basil sauce.' },
  { name: 'MIX SAUCE CHICKEN PASTA', price: 300, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Pink sauce pasta loaded with grilled chicken and cheese.' },
  { name: 'CHICKEN BARBECUE', price: 250, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Grilled chicken glazed with smoky sweet barbecue sauce.' },
  { name: 'VEG MIX GRILLED SIZZLER', price: 200, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Sizzling hot plate with grilled vegetables, french fries, and barbecue sauce.' },
  { name: 'MIX VEG TANDOORI SIZZLER', price: 350, cat: 'Continental & Sizzlers', veg: true, jain: false, desc: 'Sizzling tandoori paneer, kebabs, and butter rice with pepper sauce.' },
  { name: 'CHICKEN TIKKA SIZZLER', price: 400, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Sizzling chicken tikka served with buttered rice and crispy fries.' },
  { name: 'MIX CHICKEN SIZZLER', price: 400, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Platter of assorted grilled chicken skewers on a piping hot sizzler plate.' },
  { name: 'MIX NON VEG SIZZLER', price: 550, cat: 'Continental & Sizzlers', veg: false, jain: false, desc: 'Grand sizzler with chicken, mutton, prawns, and grilled accompaniments.' },

  // 13. SWEET MEMORIES (Desserts)
  { name: 'FRESH FRUITE PLATTER', price: 200, cat: 'Desserts', veg: true, jain: true, desc: 'Chef selection of seasonal sliced fruits.' },
  { name: 'HOT GULAB JAMUN', price: 110, cat: 'Desserts', veg: true, jain: true, desc: 'Two hot melt-in-mouth milk mawa dumplings soaked in cardamom sugar syrup.' },
  { name: 'RICE KHEER', price: 90, cat: 'Desserts', veg: true, jain: true, desc: 'Traditional slow-cooked basmati rice pudding infused with saffron and nuts.' },
  { name: 'GAJAR HALWA (SEASONAL)', price: 120, cat: 'Desserts', veg: true, jain: true, desc: 'Slow-cooked grated red carrots with pure ghee, mawa, and cashews.' },
  { name: 'HOT GULAB JAMUN WITH ICE-CREAM', price: 150, cat: 'Desserts', veg: true, jain: true, desc: 'Piping hot gulab jamun paired with a scoop of chilled vanilla ice cream.' },
  { name: 'VANILLA ICE-CREAM', price: 80, cat: 'Desserts', veg: true, jain: true, desc: 'Classic double scoop vanilla dairy ice cream.' },
  { name: 'VANILLA ICE-CREAM WITH HOT CHOCOLATE SAUCE', price: 150, cat: 'Desserts', veg: true, jain: true, desc: 'Vanilla ice cream drenched in warm decadent chocolate sauce.' },
  { name: 'STRAWBERRY ICE-CREAM', price: 80, cat: 'Desserts', veg: true, jain: true, desc: 'Sweet strawberry dairy ice cream.' },
  { name: 'PLAIN PISTA', price: 80, cat: 'Desserts', veg: true, jain: true, desc: 'Traditional pistachio flavored ice cream.' },
  { name: 'KESAR PISTA', price: 100, cat: 'Desserts', veg: true, jain: true, desc: 'Royal saffron and roasted pistachio rich ice cream.' },
  { name: 'BUTTER SCOTCH', price: 110, cat: 'Desserts', veg: true, jain: true, desc: 'Creamy butterscotch ice cream with crunchy praline bits.' },
  { name: 'CHOCOLATE ICE-CREAM', price: 110, cat: 'Desserts', veg: true, jain: true, desc: 'Rich Dutch chocolate ice cream scoop.' }
];

console.log('Total Menu Items extracted:', RAW_MENU_DATA.length);
fs.writeFileSync(path.join(__dirname, 'hotel_elite_inn_menu.json'), JSON.stringify(RAW_MENU_DATA, null, 2));
